### PR TITLE
Fix pir8spk

### PR DESCRIPTION
**Pull request by nabijaczleweli**

### CODE REVIEW

**Comment by thecoshman** [comment]
No, "would've" is correct here, as in "You are bad because you would have used a DB" (when you didn't need to). Of course you 'could have' used a database, but what does that mean?

**Comment by nabijaczleweli** [comment]
Hand-rolled solution as opposed to a DB

**Comment by thecoshman** [comment]
Why does it make someone a badlet because they could have done something?

**Comment by thecoshman** [comment]
I don't like the fact this contradicts another reason. I'll look at adding a way to link to specific reasons, then maybe this can re-added. But until then...

**Pull request closed without merging**
